export interface Billboard {
  id: string;
  title: string;
  location: string;
  city: string;
  price: number;
  image: string;
  type: "Hoarding" | "Digital" | "Unipole" | "Bus Shelter";
  size: string;
  trafficEstimate: string;
  tags: string[];
  lat: number;
  lng: number;
}

export interface BillboardReview {
  id: string;
  billboardId: string;
  user: string;
  rating: number;
  comment: string;
  date: string;
}

export const billboards: Billboard[] = [
  {
    id: "1",
    title: "MG Road Premium Hoarding",
    location: "MG Road, Near Brigade Gateway",
    city: "Bangalore",
    price: 25000,
    image: "billboard-1",
    type: "Hoarding",
    size: "40ft × 20ft",
    trafficEstimate: "1.2L+ daily impressions",
    tags: ["High Traffic", "Premium"],
    lat: 12.9716,
    lng: 77.5946,
  },
  {
    id: "2",
    title: "Andheri Digital Billboard",
    location: "Western Express Highway, Andheri",
    city: "Mumbai",
    price: 35000,
    image: "billboard-2",
    type: "Digital",
    size: "30ft × 15ft",
    trafficEstimate: "2.5L+ daily impressions",
    tags: ["Digital", "Popular"],
    lat: 19.1136,
    lng: 72.8697,
  },
  {
    id: "3",
    title: "NH-48 Highway Unipole",
    location: "NH-48, Near Manesar Toll",
    city: "Gurugram",
    price: 12000,
    image: "billboard-3",
    type: "Unipole",
    size: "50ft × 25ft",
    trafficEstimate: "80K+ daily impressions",
    tags: ["Budget Friendly", "Highway"],
    lat: 28.4595,
    lng: 77.0266,
  },
  {
    id: "4",
    title: "T Nagar Market Billboard",
    location: "Usman Road, T Nagar",
    city: "Chennai",
    price: 18000,
    image: "billboard-4",
    type: "Hoarding",
    size: "30ft × 15ft",
    trafficEstimate: "1.5L+ daily impressions",
    tags: ["High Traffic", "Market Area"],
    lat: 13.0418,
    lng: 80.2341,
  },
  {
    id: "5",
    title: "Connaught Place Digital",
    location: "Rajiv Chowk, Connaught Place",
    city: "Delhi",
    price: 35000,
    image: "billboard-1",
    type: "Digital",
    size: "25ft × 12ft",
    trafficEstimate: "3L+ daily impressions",
    tags: ["Premium", "Landmark"],
    lat: 28.6315,
    lng: 77.2167,
  },
  {
    id: "6",
    title: "Salt Lake Sector V Hoarding",
    location: "Sector V, Near TCS Office",
    city: "Kolkata",
    price: 8000,
    image: "billboard-3",
    type: "Hoarding",
    size: "35ft × 18ft",
    trafficEstimate: "60K+ daily impressions",
    tags: ["Budget Friendly", "IT Hub"],
    lat: 22.5726,
    lng: 88.3639,
  },
  {
    id: "7",
    title: "Bandra-Worli Sea Link Billboard",
    location: "Bandra-Worli Sea Link Entry",
    city: "Mumbai",
    price: 32000,
    image: "billboard-2",
    type: "Digital",
    size: "35ft × 18ft",
    trafficEstimate: "2L+ daily impressions",
    tags: ["Premium", "Landmark"],
    lat: 19.0380,
    lng: 72.8198,
  },
  {
    id: "8",
    title: "Koramangala Bus Shelter Ad",
    location: "80 Feet Road, Koramangala",
    city: "Bangalore",
    price: 5000,
    image: "billboard-4",
    type: "Bus Shelter",
    size: "6ft × 4ft",
    trafficEstimate: "40K+ daily impressions",
    tags: ["Budget Friendly", "Residential"],
    lat: 12.9352,
    lng: 77.6245,
  },
  {
    id: "9",
    title: "Hinjewadi IT Park Unipole",
    location: "Hinjewadi Phase 1 Entry",
    city: "Pune",
    price: 15000,
    image: "billboard-3",
    type: "Unipole",
    size: "45ft × 20ft",
    trafficEstimate: "90K+ daily impressions",
    tags: ["IT Hub", "High Traffic"],
    lat: 18.5912,
    lng: 73.7390,
  },
  {
    id: "10",
    title: "Anna Salai Digital Display",
    location: "Anna Salai, Near Gemini Flyover",
    city: "Chennai",
    price: 28000,
    image: "billboard-1",
    type: "Digital",
    size: "28ft × 14ft",
    trafficEstimate: "1.8L+ daily impressions",
    tags: ["Digital", "High Traffic"],
    lat: 13.0604,
    lng: 80.2496,
  },
  {
    id: "11",
    title: "Jubilee Hills Hoarding",
    location: "Road No. 36, Jubilee Hills",
    city: "Hyderabad",
    price: 22000,
    image: "billboard-2",
    type: "Hoarding",
    size: "40ft × 20ft",
    trafficEstimate: "1.1L+ daily impressions",
    tags: ["Premium", "Residential"],
    lat: 17.4310,
    lng: 78.4072,
  },
  {
    id: "12",
    title: "SG Highway Bus Shelter",
    location: "SG Highway, Near Iskcon",
    city: "Ahmedabad",
    price: 6000,
    image: "billboard-4",
    type: "Bus Shelter",
    size: "6ft × 4ft",
    trafficEstimate: "35K+ daily impressions",
    tags: ["Budget Friendly", "Popular"],
    lat: 23.0225,
    lng: 72.5714,
  },
  {
    id: "13",
    title: "MG Road Metro Station Billboard",
    location: "MG Road Metro Exit",
    city: "Delhi",
    price: 20000,
    image: "billboard-1",
    type: "Hoarding",
    size: "30ft × 15ft",
    trafficEstimate: "1.5L+ daily impressions",
    tags: ["High Traffic", "Landmark"],
    lat: 28.6328,
    lng: 77.2197,
  },
  {
    id: "14",
    title: "Marine Drive Seaface Unipole",
    location: "Marine Drive, Near Chowpatty",
    city: "Mumbai",
    price: 30000,
    image: "billboard-3",
    type: "Unipole",
    size: "40ft × 20ft",
    trafficEstimate: "2L+ daily impressions",
    tags: ["Premium", "Landmark"],
    lat: 18.9548,
    lng: 72.8138,
  },
  {
    id: "15",
    title: "Whitefield Bus Shelter Ad",
    location: "ITPL Main Road, Whitefield",
    city: "Bangalore",
    price: 5500,
    image: "billboard-4",
    type: "Bus Shelter",
    size: "6ft × 4ft",
    trafficEstimate: "45K+ daily impressions",
    tags: ["Budget Friendly", "IT Hub"],
    lat: 12.9698,
    lng: 77.7500,
  },
  {
    id: "16",
    title: "Noida Expressway Digital",
    location: "Noida-Greater Noida Expressway",
    city: "Noida",
    price: 27000,
    image: "billboard-2",
    type: "Digital",
    size: "35ft × 18ft",
    trafficEstimate: "1.3L+ daily impressions",
    tags: ["Highway", "Digital"],
    lat: 28.5355,
    lng: 77.3910,
  },
];

export const billboardReviews: BillboardReview[] = [
  { id: "r1", billboardId: "1", user: "Rahul M.", rating: 5, comment: "Excellent visibility, our brand reach increased 40% in just 2 weeks!", date: "2025-02-15" },
  { id: "r2", billboardId: "1", user: "Priya S.", rating: 4, comment: "Great location, slightly expensive but worth it for the traffic.", date: "2025-01-20" },
  { id: "r3", billboardId: "2", user: "Amit K.", rating: 5, comment: "Digital display quality is stunning. Got a lot of customer inquiries.", date: "2025-03-01" },
  { id: "r4", billboardId: "2", user: "Sneha R.", rating: 4, comment: "Good impressions count, happy with the campaign results.", date: "2025-02-10" },
  { id: "r5", billboardId: "3", user: "Vikram P.", rating: 4, comment: "Great highway visibility. Perfect for our logistics brand.", date: "2025-01-28" },
  { id: "r6", billboardId: "4", user: "Deepa N.", rating: 5, comment: "T Nagar market crowd loved our ad. Sales jumped 25%!", date: "2025-02-20" },
  { id: "r7", billboardId: "5", user: "Arjun D.", rating: 5, comment: "Premium location, premium results. Couldn't ask for more.", date: "2025-03-05" },
  { id: "r8", billboardId: "5", user: "Kavitha L.", rating: 4, comment: "Expensive but the footfall justifies the cost completely.", date: "2025-02-25" },
  { id: "r9", billboardId: "6", user: "Sourav G.", rating: 4, comment: "Budget friendly and decent reach in the IT corridor.", date: "2025-01-15" },
  { id: "r10", billboardId: "7", user: "Meera T.", rating: 5, comment: "Sea link billboard is iconic. Our brand got massive visibility.", date: "2025-03-10" },
  { id: "r11", billboardId: "8", user: "Ravi K.", rating: 3, comment: "Small size but decent for local campaigns in the area.", date: "2025-02-05" },
  { id: "r12", billboardId: "9", user: "Ananya B.", rating: 4, comment: "IT crowd sees this daily. Great for tech product launches.", date: "2025-03-08" },
  { id: "r13", billboardId: "10", user: "Karthik S.", rating: 5, comment: "Anna Salai is always busy. Amazing digital display quality.", date: "2025-02-18" },
  { id: "r14", billboardId: "11", user: "Pooja R.", rating: 4, comment: "Jubilee Hills is posh locality, perfect for luxury brands.", date: "2025-03-02" },
  { id: "r15", billboardId: "14", user: "Nikhil J.", rating: 5, comment: "Marine Drive unipole is unmissable. Best ROI we've ever had.", date: "2025-03-12" },
];
